# Generated by Django 3.2.5 on 2022-12-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupark', '0003_alter_parkingreservation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
